[INFR] PDF validation added to CI-Workflow

diff --git a/.github/workflows/build.ci.yml b/.github/workflows/build.ci.yml
--- a/.github/workflows/build.ci.yml
+++ b/.github/workflows/build.ci.yml
@@ -28,6 +28,9 @@ env:
   VALIDATORSCENARIOFILENAME: scenarios.xml
   PHPDOCUMENTORURL: https://phpdoc.org/phpDocumentor.phar
   PHPDOCUMENTORFILENAME: phpDocumentor.phar
+  VERAPDFURL: https://software.verapdf.org/rel/verapdf-installer.zip
+  VERAPDFPATH: build/verapdf
+  VERAPDFZIPFILENAME: verapdf.zip
 
 jobs:
   build:
@@ -145,6 +148,36 @@ jobs:
           php -f examples/En16931SimpleQuick.php
           java -jar $VALIDATORPATH/$VALIDATORJARFILENAME -r $VALIDATORPATH -s $VALIDATORPATH/$VALIDATORSCENARIOFILENAME examples/factur-x.xml
           rm -rf build/validator
+
+      - name: Run Tests (VeraPDF)
+        continue-on-error: true
+        run: |
+          set -e
+          rm -rf $VERAPDFPATH
+          mkdir $VERAPDFPATH
+          wget $VERAPDFURL -O $VERAPDFPATH/$VERAPDFZIPFILENAME
+          unzip -j $VERAPDFPATH/$VERAPDFZIPFILENAME -d $VERAPDFPATH
+          rm -f $VERAPDFPATH/$VERAPDFZIPFILENAME
+          echo "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>
+            <AutomatedInstallation langpack=\"eng\">
+                <com.izforge.izpack.panels.htmlhello.HTMLHelloPanel id=\"welcome\"/>
+                <com.izforge.izpack.panels.target.TargetPanel id=\"install_dir\">
+                    <installpath>$VERAPDFPATH</installpath>
+                </com.izforge.izpack.panels.target.TargetPanel>
+                <com.izforge.izpack.panels.packs.PacksPanel id=\"sdk_pack_select\">
+                    <pack index=\"0\" name=\"veraPDF Mac and *nix Scripts\" selected=\"true\"/>
+                    <pack index=\"1\" name=\"veraPDF Validation model\" selected=\"true\"/>
+                    <pack index=\"2\" name=\"veraPDF Documentation\" selected=\"true\"/>
+                    <pack index=\"3\" name=\"veraPDF Sample Plugins\" selected=\"true\"/>
+                </com.izforge.izpack.panels.packs.PacksPanel>
+                <com.izforge.izpack.panels.install.InstallPanel id=\"install\"/>
+                <com.izforge.izpack.panels.finish.FinishPanel id=\"finish\"/>
+            </AutomatedInstallation>" > $VERAPDFPATH/install.xml
+          VERAPDFINSTALLJAR=$(find $VERAPDFPATH -type f -name "*.jar" | head -n 1); [[ -z "$VERAPDFINSTALLJAR" ]] && { echo "No veraPDF installer found" >&2; exit 1; } || echo "veraPDF installer fount at $VERAPDFINSTALLJAR"
+          java -jar $VERAPDFINSTALLJAR $VERAPDFPATH/install.xml
+          php -f examples/En16931SimpleWithPdf.php
+          VERAPDFRESULT=$($VERAPDFPATH/verapdf --format text examples/fullpdf.pdf)
+          [[ $VERAPDFRESULT == PASS* ]] || { echo "Error: PDF validation not passed" >&2; exit 1; }
 
       - name: Publish Unit Test Results
         uses: EnricoMi/publish-unit-test-result-action@v2
