[INFR] Fix veraPDF validation in CI workflow

diff --git a/.github/workflows/build.ci.yml b/.github/workflows/build.ci.yml
--- a/.github/workflows/build.ci.yml
+++ b/.github/workflows/build.ci.yml
@@ -175,9 +175,13 @@ jobs:
             </AutomatedInstallation>" > $VERAPDFPATH/install.xml
           VERAPDFINSTALLJAR=$(find $VERAPDFPATH -type f -name "*.jar" | head -n 1); [[ -z "$VERAPDFINSTALLJAR" ]] && { echo "No veraPDF installer found" >&2; exit 1; } || echo "veraPDF installer fount at $VERAPDFINSTALLJAR"
           java -jar $VERAPDFINSTALLJAR $VERAPDFPATH/install.xml
+          echo "Creating test PDF"
           php -f examples/En16931SimpleWithPdf.php
+          echo "Running PDF validation"
           VERAPDFRESULT=$($VERAPDFPATH/verapdf --format text examples/fullpdf.pdf)
-          [[ $VERAPDFRESULT == PASS* ]] || { echo "Error: PDF validation not passed" >&2; exit 1; }
+          echo "Result of validation"
+          echo $VERAPDFRESULT
+          [[ $VERAPDFRESULT == PASS* ]] && echo "PDF validation passed" || { echo "Error: PDF validation not passed" >&2; exit 1; }
 
       - name: Publish Unit Test Results
         uses: EnricoMi/publish-unit-test-result-action@v2
